# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '0 1 * * *'  # 每天运行一次
  

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        only-issues: true
        days-before-stale: 30
        days-before-close: 7

        stale-issue-label: stale
        stale-pr-label: stale

        stale-issue-message: >
          This issue has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs.

        close-issue-message: >
          This issue was closed because it has been inactive for a long time.

        stale-pr-message: >
          This PR has been marked as stale due to inactivity.

        close-pr-message: >
          Closing this PR due to inactivity.
